version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:12.19.0
        
    steps:
      - run: npm install
      - run: npm test

